version: '2'
services:

#  casino:
#    image: yiisoftware/yii2-php:7.4-apache
#    build:
#      context: .
#      dockerfile: docker/web/Dockerfile
#    volumes:
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
#      - ./:/app:delegated
#    ports:
#      - '8800:80'


    php:
      image: yiisoftware/yii2-php:7.1-apache
      volumes:
        - ~/.composer-docker/cache:/root/.composer/cache:delegated
        - ./:/app:delegated
      ports:
        - '8000:80'

#  mysql:
#    image: mysql:5.7
#    restart: always
#    logging:
#      driver: syslog
#      options:
#        tag: "DOCKER:{{.Name}}"
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
#      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
#      MYSQL_DATABASE: ${MYSQL_DB_NAME}
#      MYSQL_USER: ${MYSQL_DB_USER}
#      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
#    ports:
#      - 3306:3306
#    volumes:
#      - ./docker/databases/mysql:/var/lib/mysql
